function createfigure1(X1, Y1)
%CREATEFIGURE1(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 01-Mar-2013 17:26:43

% Create figure
figure1 = figure('PaperSize',[20.98404194812 29.67743169791]);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0729833546734955 0.074766355140187 0.882478830200454 0.878901598527767]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-3.71747211895909 3996.28252788104]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-155.609756097561 24.390243902439]);
%% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 2]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1);

% Create title
title('Frequency Response');

% Create xlabel
xlabel('Frequency(Hz)');

% Create ylabel
ylabel('Amplitude(dB)');

% Create line
annotation(figure1,'line',[0.0734375 0.955208333333333],...
    [0.585170212765957 0.586170212765957],'Color',[1 0 0]);

% Create line
annotation(figure1,'line',[0.130729166666667 0.130729166666667],...
    [0.0308510638297872 0.948936170212766],'Color',[1 0 0]);

% Create line
annotation(figure1,'line',[0.560416666666667 0.560416666666667],...
    [0.0446808510638298 0.953191489361702],'Color',[1 0 0]);

% Create line
annotation(figure1,'line',[0.171354166666667 0.171354166666667],...
    [0.953191489361702 0.0297872340425532],'Color',[1 0 0]);

% Create textbox
annotation(figure1,'textbox',...
    [0.5619375 0.0897196261682244 0.0949662656903766 0.0443229270232652],...
    'String',{'2200 Hz'},...
    'FitBoxToText','off',...
    'BackgroundColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.166234875160051 0.0841121495327106 0.0806270495261414 0.0411214953271027],...
    'String',{'450 Hz'},...
    'FitBoxToText','off',...
    'BackgroundColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.0755421734955186 0.2 0.080664242125123 0.0444762378206406],...
    'String',{'260 Hz'},...
    'FitBoxToText','off',...
    'BackgroundColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.868182320434589 0.592360003039288 0.0704508734287308 0.0464448200437469],...
    'String',{'50 dB'},...
    'FitBoxToText','off',...
    'BackgroundColor',[1 1 1]);

